# Autogenerated wrapper script for KaHyPar_jll for x86_64-linux-musl
export libkahypar

using boost_jll
JLLWrappers.@generate_wrapper_header("KaHyPar")
JLLWrappers.@declare_library_product(libkahypar, "libkahypar.so")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll)
    JLLWrappers.@init_library_product(
        libkahypar,
        "lib/libkahypar.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
