# Autogenerated wrapper script for KaHyPar_jll for x86_64-apple-darwin
export libkahypar

using boost_jll
JLLWrappers.@generate_wrapper_header("KaHyPar")
JLLWrappers.@declare_library_product(libkahypar, "@rpath/libkahypar.dylib")
function __init__()
    JLLWrappers.@generate_init_header(boost_jll)
    JLLWrappers.@init_library_product(
        libkahypar,
        "lib/libkahypar.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
